f_var = "x_0"
f_add = "add_2"
f_times = "times_2"
f_cos = "cos_1"
f_sin = "sin_1"
f_minus = "minus_1"
f_relation = "relation_2"
f_norm = "norm_1"
f_sum = "sum_1"
f_square = "square_1"
f_int = "defi_integral_4"
f_leq = "leq_2"
f_geq = "geq_2"
f_equal = "equal_2"
f_and = "f_and_2"
f_implies = "f_implies_1"
f_answer = "f_answer_1"


is_ordered_set = "is_ordered_set_0"
is_least_upper_bound = "is_least_upper_bound_0"
is_not_empty = "is_not_empty_0"
is_subset_of = "is_subset_of_0"
is_bounded_below = "is_bounded_below_0"
is_inf_exist = "is_inf_exit_0"

# is_ordered_set = "is_ordered_set_1"
# is_least_upper_bound = "is_least_upper_bound_1"
# is_not_empty = "is_not_empty_1"
# is_subset_of = "is_subset_of_1"
# is_bounded_below = "is_bounded_below_1"
# is_inf_exist = "is_inf_exit_1"